
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seaohhvghqynuzdwsylg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlYW9oaHZnaHF5bnV6ZHdzeWxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTkwMjksImV4cCI6MjA2MzkzNTAyOX0.Vs9hWXmhBUPhEFhxmwQzHj-_tPPaPVcnlDCDRt5Myv0";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true
  }
});
